<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [2]:
import numpy as np

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [4]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [5]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [6]:
print(py_real_names[0])
py_super_names[0]

Natasha Romanoff


'Black Widow'

Negative index counts from the **back** of the list

In [7]:
print(py_real_names[-1])
#should return last name

Stephen Strange


## 1.3 Accessing data from a dictionary

In [8]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}       

print(superhero_info["Natasha Romanoff"])

Black Widow


In [9]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [10]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [11]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [13]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

print(len(py_list_2d))
print(len(np_array_2d))
np_array_2d.shape

10
10


(10, 2)

## 2.2 Arrays are fussy about type

In [16]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [18]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
#np_list + 10  (doesn't work)       
np_array + 10

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [20]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2)

np_array_1 + np_array_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [22]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 


print(py_list*2)

np_array*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

#print(py_list**2) doesn't work
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)     

py_list == 3     # Works, but what IS the question?
# The question is if py_list, which is a list, is the same as 3, an integer.

np_array == 3
# The question is if each item in the array is equal to 3.

array([False, False,  True, False, False])

## 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [26]:
sum(py_list)     # sum() is a base Python function

15

In [27]:
max(py_list)     # max() is a base Python function

5

In [28]:
min(py_list)     # min() is a base Python function

1

In [29]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [30]:
np_array.sum()

15

In [31]:
np_array.max()

5

In [32]:
np_array.min()

1

In [33]:
np_array.mean()

3.0

In [34]:
np_array.std()

1.4142135623730951

These functions work with numpy arrays.